Repository lab-brussels-1/Group-3-separation-of-concerns-starter, pull requests merged in 2022-08, with the labels that each got.

#2 update communication file
  planning/communication-plan.md
  planning/constraints.md
Labels: communication

#5 PR_Wireframe
  .DS_Store
  .cspell.json
  images/.DS_Store
  images/LIST_EXERCISE.png
  planning/wireframe.md
Labels: documentation, MD

#6 PR_modification of development strategy
  planning/development-strategy.md
Labels: documentation, MD

#11 updated development stratergu file
  planning/backlog.md
  planning/development-strategy.md
Labels: MD

#13 PR_Wireframe2
  .DS_Store
  images/.DS_Store
  images/wireframe2.png
  planning/backlog.md
  planning/wireframe.md
Labels: documentation, MD

#16 update html css file
  .DS_Store
  .vscode/settings.json
  client/styles/index.css
  images/prototype.png
  images/screenshot.png
  index.html
  planning/README.md
Labels: html, css

#20 add js file
  .eslintrc.json
  .vscode/settings.json
  client/data/constants.js
  client/data/state.js
  client/src/handlers/add-contact.js
  client/src/init.js
  client/src/listeners/add-contact.js
  client/src/utils/add-contact.js
  client/styles/index.css
Labels: js
